# Generated by Django 4.2.1 on 2023-06-05 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0002_alter_persona_is_vendedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='is_vendedor',
            field=models.BooleanField(default=True),
        ),
    ]
