# Generated by Django 4.2.1 on 2023-05-28 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0002_alumno'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alumno',
        ),
    ]
