# Generated by Django 4.2.1 on 2023-06-13 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0004_alter_persona_is_vendedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id_carrito', models.AutoField(primary_key=True, serialize=False)),
                ('id_persona', models.ForeignKey(db_column='idPersona', on_delete=django.db.models.deletion.CASCADE, to='paginas.persona')),
                ('id_producto', models.ForeignKey(db_column='idProducto', on_delete=django.db.models.deletion.CASCADE, to='paginas.producto')),
            ],
        ),
    ]
