# Generated by Django 4.2.1 on 2023-06-18 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0005_carrito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='id_persona',
        ),
        migrations.AddField(
            model_name='carrito',
            name='descripcion_producto',
            field=models.TextField(default=False),
        ),
        migrations.AddField(
            model_name='carrito',
            name='nombre_producto',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='carrito',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=False, max_digits=10),
        ),
    ]
