# Generated by Django 4.2.1 on 2023-05-31 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0006_vendedor_delete_alumno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(db_column='idCategoria', primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='vendedor',
            name='img',
        ),
        migrations.AddField(
            model_name='vendedor',
            name='img_trabajador',
            field=models.ImageField(null=True, upload_to='vendedor'),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='apellido_materno',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='apellido_paterno',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='nombre',
            field=models.CharField(max_length=60),
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=60)),
                ('precio', models.IntegerField(max_length=20)),
                ('img_producto', models.ImageField(null=True, upload_to='productos')),
                ('descripcion', models.CharField(max_length=60)),
                ('stock', models.IntegerField()),
                ('id_categoria', models.ForeignKey(db_column='idCategoria', on_delete=django.db.models.deletion.CASCADE, to='paginas.categoria')),
            ],
        ),
    ]
