# Generated by Django 4.2.1 on 2023-05-31 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0007_categoria_remove_vendedor_img_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productos',
            old_name='img_producto',
            new_name='imagen',
        ),
        migrations.RenameField(
            model_name='vendedor',
            old_name='img_trabajador',
            new_name='imagen',
        ),
        migrations.AlterField(
            model_name='productos',
            name='descripcion',
            field=models.CharField(max_length=210),
        ),
        migrations.AlterField(
            model_name='productos',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
