# Generated by Django 4.2.1 on 2023-06-02 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0008_rename_img_producto_productos_imagen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='stock',
        ),
    ]
