# Generated by Django 4.2.1 on 2023-06-02 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0010_rename_productos_producto_rename_vendedor_vendedores'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vendedores',
            new_name='Vendedor',
        ),
    ]
