# Generated by Django 4.2.1 on 2023-06-02 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0014_alter_producto_imagen_alter_vendedor_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to='producto'),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to='vendedor'),
        ),
    ]
