# Generated by Django 4.2.1 on 2023-06-02 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0015_alter_producto_imagen_alter_vendedor_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(verbose_name=1),
        ),
    ]
