# Generated by Django 4.2.1 on 2023-06-02 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0016_alter_producto_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(verbose_name=0),
        ),
    ]
