# Generated by Django 4.2.1 on 2023-06-03 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0020_remove_persona_fecha_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='fecha_nacimiento',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='rut',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
