# Generated by Django 4.2.1 on 2023-06-03 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0021_persona_fecha_nacimiento_alter_persona_rut'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='apellido_materno',
            new_name='apellido',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='apellido_paterno',
        ),
    ]
