# Generated by Django 4.2.1 on 2023-06-03 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0022_rename_apellido_materno_persona_apellido_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='rut',
            new_name='id_producto',
        ),
    ]
