# Generated by Django 4.2.1 on 2023-06-03 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0023_rename_rut_persona_id_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='fecha_nacimiento',
        ),
        migrations.AlterField(
            model_name='persona',
            name='activo',
            field=models.IntegerField(null=True),
        ),
    ]
