# Generated by Django 4.2.1 on 2023-06-03 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0024_remove_persona_direccion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='id_producto',
            new_name='id_persona',
        ),
        migrations.AlterField(
            model_name='persona',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
