# Generated by Django 4.2.1 on 2023-06-04 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0025_rename_id_producto_persona_id_persona_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='activo',
            field=models.IntegerField(),
        ),
    ]
