# Generated by Django 4.2.1 on 2023-06-04 06:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0029_carrito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='productos',
        ),
        migrations.AlterField(
            model_name='carrito',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='paginas.persona'),
        ),
        migrations.AddField(
            model_name='carrito',
            name='productos',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='paginas.producto'),
            preserve_default=False,
        ),
    ]
