# Generated by Django 4.2.1 on 2023-06-04 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0030_remove_carrito_productos_alter_carrito_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='activo',
            field=models.BooleanField(default=False),
        ),
    ]
