# Generated by Django 4.2.1 on 2023-06-04 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0037_alter_persona_activo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Persona',
        ),
    ]
