# Generated by Django 4.2.1 on 2023-06-04 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0039_persona_delete_carrito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
