# Generated by Django 4.2.1 on 2023-06-04 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0041_alter_persona_activo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Persona',
        ),
    ]
