# Generated by Django 4.2.1 on 2023-06-04 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0042_delete_persona'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genero',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='id_categoria',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
