# Generated by Django 4.2.1 on 2023-06-04 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0044_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='activo',
        ),
    ]
