# Generated by Django 4.2.1 on 2023-06-04 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0045_remove_persona_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
