# Generated by Django 4.2.1 on 2023-06-04 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0047_user_remove_persona_activo_persona_is_vendedor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='user',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='paginas.user'),
        ),
    ]
